config/routes.rb
Rails.application.routes.draw do
  resources :songs, only: [:index, :show] do

end

root "songs#index"    

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :songs
  validates :body, presence: true, length: { minimum: 2}

end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/song.rb
class Song < ActiveRecord::Base
   has_many :likes, dependent: :nullify
   has_many :comments, dependent: :nullify
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  belongs_to :songs

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
#  before_action :lookup_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end
  
  def new
    #@item = @item_type.items.new
  end
  
  def create
  #  @item = @item_type.items.new(item_params)
  #    if @item.save
  #      @item.get_image
  #      redirect_to root_path, notice: "Sucess! We added your Item!"
  #    else
  #      render 'new'
  #  end
  end
  
  def edit
  #  @item = @item_type.items.find(params[:id])
  end

  def update
  #  @item = update_attributes(params[:id])
  #  @item.get_image unless !@item.image_url.nil?
  #    if @item.update_attributes(item_params)
  #      redirect_to root_path, notice: "Sucess! We saved #{@item.title}!!"
  #    else
  #      render 'new'
  #  end
  end

  def destroy
  #  @item = destroy
  #  @item.destroy
  #  redirect_to root_path, notice: ":( It's gone!"
  end

private
# this is run before every action is started

def lookup_item_type
#  @item_type = ItemType.find(params[:item_type_id])
end

def lookup_song
  @song = Song.find(params[:id])
end

def song_params
  params.require(:song).permit(:title, :body)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/_footer.html.erb
<div>
<footer class="footer">
  <p><%= link_to 'Home', root_path %></p>
  <hr />
  <small>
    <p>Format and Boostrap stuff from<br/>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a><br />
    
    Overall Project by <a href="http://mowen.imgd.ca/nextweb/">Mike Owen</a>
    </p>
  </small>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <!-- <%= link_to "sample app", '#', id: "logo" %> -->
    <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to "Show",   '#' %></li>
          <li><%= link_to "NicGuy59",   'http://mowen.imgd.ca/nextweb/' %></li>          
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/_song.html.erb
<div class="row">
    <div id="leftCol" class="col-xs-9">
      <h3><%= song.title %></h3>
      
      <% end %>
    </div>

    <div id="rightcol" class="col-xs-3">
      <p><%= image_tag(song.image_url, alt: "", class: 'thumb')  %></p> 
    </div>
</div>  

<div class="row">
   <div class="col-xs-12">
  
    <!-- <p>
    <%= link_to 'Edit', edit_song_path(item) %>
    *
    <%= link_to 'Delete', song_path(song), method: :delete %>
    </p>

    <!-- <p>Click here for more about: <%= link_to(song.title, song_path(song)) %> -->
    </p>
    <hr />
   </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LLoudCloud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Structure source: "https://www.railstutorial.org/book/filling_in_the_layout" -->
<%= render 'layouts/header' %>
<div class="container">
    <%= yield %>
<%= render 'layouts/footer' %>
</div>  
</body>
</html>

app/views/songs/_song.html.erb
<p><%= link_to 'Add a new one', new_song_path(song) %></p>

  <% songs.each do |song| %> 
    <%= render song %>
    <p><%= link_to song.title, song_path(song) %></p>
  <% end %>

app/views/songs/index.html.erb
<div class="row">
<div class="col-xs-12">
<h1>LoudCloud</h1>
<p>We have <%= @songs.count %> Songs!</p>
<p><%= link_to 'New Song', song_path(@songs) %></p> -->
</div>
</div>
<div>
<hr />
<!-- <%= render 'layouts/song' %>  -->
</div> 